#+title: Lucida

** Basic Facts
- Name: Lucida. Ancient Latin name.
- Pronouns: It/Its, She/Her
** Backstory
*** Summary
Lucida is the last of the Camenae. When the world was covered in water, the Camenae were the intelligent inhabitants thereof, but they were killed by their own biology. In the time since the Camenae's extinction, she made a Covenant with a cursed god, Epichysis, allowing her to enter into human society.
*** History of the Camenae
The Camenae (from Latin for goddesses of fresh water) had no natural causes of death, leading to two things: one, wisdom beyond that imaginable to humans--avoiding conflict and unnatural causes of death; two, they also had no natural cap on the size to which they could grow--the thing that ultimately led to the extinction of the species, except for Lucida.
*** Personal History of Lucida
Lucida is the Last Child of the Camenae, both literally and figuratively. By the time Lucida reached maturity, the last of the adult Camenae were starving.

Her memories of the other Camenae are fleeting as her time with them was short in the span of her life. When the last of her species died, it fled to the deepest parts of the Earth, settling on the ocean floor to starve and join her kin in death. Yet, she did not.

In its time at the Depth of the World, hundreds of thousands of years passed. At some point in those reaches of prehistory, a presence made a promise to Lucida: if it were to create a human vessel for it, the Camenae would live again. Lucida has a sense that this god, Epichysis (Latin for Vessel), is not one of benevolence, and carries an energy of not only negativity, but of a curse. Yet, in all its time, Lucida had no other no hope, no other constant--Epichysis was her life.

In the time Lucida spent in complete isolation, the world had shifted. Dry land exists above the waters the Camenae once inhabited. In that time immemorial, the only living thing that existed on Earth was Lucida. Yet, in the moments Lucida made the covenant with Epichysis, stirrings of life began again on the planet. It's impossible to know if it was Epichysis itself that created that life, but what can be known is that the penultimate form of that life is humanity.

As a part of the Covenant, Lucida gained form a human/generally humanoid form that allowed her to enter human society, with it doing so in the time of the Roman Empire--that being the reason for her name, and language around her people being derived from ancient Latin. Her life in human forms has been defined by two continuous tragedies thus far: one, her immortality destroying any chances for genuine connection with humans; and two, a paralyzing fear that humans will die off just as the Camenae did and leave her completely alone again. As such, the only constant she feels it can rely upon is Epichysis--contradictory as that may be with her love for humans.

She has survived through every era of human history since; embracing those short times she was able to spend with the fleeting members of the species, but lacking a purpose. This is where we are now, new to DIVISION, Lucida hopes for purpose among those more like her, but remains skeptical of her chances for happiness.
